### ISSUE TITLE
Some dependencies are included only as `.pom` and `.module`, but `.jar` is missing

### ISSUE THREAD

**Issue by kravemir** [jwharm/flatpak-gradle-generator#3]
Hello, for this setup - https://github.com/archivekeep/archivekeep/commit/d1371e089fd3c0c0e7a011f22905619e3081410f, the plugin didn't include few JAR files, but `.module` and POM files are present in the generated output.

Manually added JAR files:

```yaml
      - type: file
        url: "https://repo.maven.apache.org/maven2/io/github/vinceglb/filekit-core-jvm/0.8.3/filekit-core-jvm-0.8.3.jar"
        sha256: "13036bf2c56432c167c4306bca37254ba80efac85bd93012240bc8f7ace28dc8"
        dest: "offline-repository/io/github/vinceglb/filekit-core-jvm/0.8.3"
        dest-filename: "filekit-core-jvm-0.8.3.jar"
      - type: file
        url: "https://repo.maven.apache.org/maven2/io/github/vinceglb/filekit-compose-jvm/0.8.3/filekit-compose-jvm-0.8.3.jar"
        sha256: "26321e1f946ce6f238d456e9e61e6d73a08a4e94157f3b5aa990420c52e164ed"
        dest: "offline-repository/io/github/vinceglb/filekit-compose-jvm/0.8.3"
        dest-filename: "filekit-compose-jvm-0.8.3.jar"
      - type: file
        url: "https://repo.maven.apache.org/maven2/org/jetbrains/compose/components/components-resources-desktop/1.7.3/components-resources-desktop-1.7.3.jar"
        sha256: "1584b739e8f1869e4f340519dc984d4a44582a80ef323e655999ddb18dd954c2"
        dest: "offline-repository/org/jetbrains/compose/components/components-resources-desktop/1.7.3"
        dest-filename: "components-resources-desktop-1.7.3.jar"
```

Generated `.module` and POM files in JSON:

```json
  {
    "type": "file",
    "url": "https://repo.maven.apache.org/maven2/io/github/vinceglb/filekit-core-jvm/0.8.3/filekit-core-jvm-0.8.3.module",
    "sha512": "f1496c66035f243613d40b4d6af23f8f12316ba69e6454ddf84be3c31e0789d0d8378cdd01a67d0631b4aeb4b04a1692517dd39c2435558a3cbe316ac1d1bc9d",
    "dest": "./offline-repository/io/github/vinceglb/filekit-core-jvm/0.8.3",
    "dest-filename": "filekit-core-jvm-0.8.3.module"
  },
  {
    "type": "file",
    "url": "https://repo.maven.apache.org/maven2/io/github/vinceglb/filekit-core-jvm/0.8.3/filekit-core-jvm-0.8.3.pom",
    "sha512": "f86bb204d3f1e6d7d3cc55f2f65458415c9df6479f3db78102f00faf2e37480f3fda5f2da2f45bc9d60cd5150bf105985acfdb1c15df458b6c292a4db96d513a",
    "dest": "./offline-repository/io/github/vinceglb/filekit-core-jvm/0.8.3",
    "dest-filename": "filekit-core-jvm-0.8.3.pom"
  },
  {
    "type": "file",
    "url": "https://repo.maven.apache.org/maven2/io/github/vinceglb/filekit-compose-jvm/0.8.3/filekit-compose-jvm-0.8.3.module",
    "sha512": "402543eb8d37869b903fc412000169b9801e4f46c482a6b0aad8b7d0c00ee61df78e759cb203856ff0a9f53d7b559f772003a4a534fd6a977a9ec0a68a7d4499",
    "dest": "./offline-repository/io/github/vinceglb/filekit-compose-jvm/0.8.3",
    "dest-filename": "filekit-compose-jvm-0.8.3.module"
  },
  {
    "type": "file",
    "url": "https://repo.maven.apache.org/maven2/io/github/vinceglb/filekit-compose-jvm/0.8.3/filekit-compose-jvm-0.8.3.pom",
    "sha512": "f9c3de632eb808676ffb50a81c0b257f0c5b536f5f2f74dbb1ba1df8f396e2f1855c77377126af19ff99f0b0bdde1f023b8f7b2e06275b8fba366f263bbb8eb2",
    "dest": "./offline-repository/io/github/vinceglb/filekit-compose-jvm/0.8.3",
    "dest-filename": "filekit-compose-jvm-0.8.3.pom"
  },
  {
    "type": "file",
    "url": "https://repo.maven.apache.org/maven2/org/jetbrains/compose/components/components-resources-desktop/1.7.3/components-resources-desktop-1.7.3.module",
    "sha512": "24e1d57602a1bd8ef2765e150abdb7fa544b00a65903f92024e80d8b0cc568299c6b187251fee840f6b46853737a86f40898522abe4cdf6be488b79fd2124fb3",
    "dest": "./offline-repository/org/jetbrains/compose/components/components-resources-desktop/1.7.3",
    "dest-filename": "components-resources-desktop-1.7.3.module"
  },
  {
    "type": "file",
    "url": "https://repo.maven.apache.org/maven2/org/jetbrains/compose/components/components-resources-desktop/1.7.3/components-resources-desktop-1.7.3.pom",
    "sha512": "da23b847700e54ff1adc7fd264d665788faad9444bdb49c847e2faae75a5c2c36243c430fbb5bc3cb29ac11e588192acfaca7f91517bb16a627bc2222411f252",
    "dest": "./offline-repository/org/jetbrains/compose/components/components-resources-desktop/1.7.3",
    "dest-filename": "components-resources-desktop-1.7.3.pom"
  },
```

It is not like this for all dependencies. For example `grpc-kotlin-stub-1.4.1` and other artifacts are included as `.jar`, `.module` and `.pom`. So, I guess, this might be something specific to those libraries.
